### ISSUE TITLE
Volumetric mean radius?

### ISSUE THREAD

**Issue by dobb13** [OpenExoplanetCatalogue/open_exoplanet_catalogue#1027]
I notice that the README.md includes some odd unit definitions that are mostly not significant, except by their secondary effects (ie the ratio between them).

The Jupiter radius is apparently based on the volumetric mean radius, whereas most material I've seen uses Earth's (or Jupiter's) equatorial radius as its basis. Either way, is the choice of mean vs equatorial significant to something in particular? Is the omission of Earth radius/mass significant?

`R_sol / R_jup`:
README: 9.96
Equatorial: 9.73

`R_jup / R_earth`:
Volumetric: 10.97
Equatorial: 11.21

It's also interesting to note that the only factors actually used anywhere are not in the catalogue, only in the web interface, and they are used for converting to units of Earths, which do not appear in the readme.

All things considered even the nominal use of equatorial radii makes less sense than a mean of an entirely different kind (`r=sqrt(eq*po)`) but no one has suggested anything like that in literature, so the point is moot.

**Comment by hannorein** [comment]
Thanks for pointing this out. I'm not sure how significant this is but I'd be happy to merge in a clarification into the readme if you want to write one.

**Comment by dobb13** [comment]
Ok, I will dig into the web interface a little too, and make the factors consistent.
