### ISSUE TITLE
Add Gaia identifiers

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#1064]
Would be good to have Gaia identifiers for the stars. As far as I'm aware, the DR2 identifiers are not necessarily the same as the DR1 identifiers, so probably best to be clear which are which.

**Comment by hannorein** [comment]
These are now included.

**Comment by hannorein** [comment]
Gaia DR2 names are now included (via SIMBAD).
