### ISSUE TITLE
Inaccessible Pages

### ISSUE THREAD

**Issue by TheDeathStar3** [OpenExoplanetCatalogue/open_exoplanet_catalogue#1095]
If I am on the home page (http://www.openexoplanetcatalogue.com/)

![Screen Shot 2020-03-01 at 3 21 06 pm](https://user-images.githubusercontent.com/54761256/75619449-efef0b80-5bcf-11ea-97dd-11b519f7d174.png)

and I go under Catalogue and click on "All extrasolar planets" I get a blank page with this written on it:

![Screen Shot 2020-03-01 at 3 21 19 pm](https://user-images.githubusercontent.com/54761256/75619451-f41b2900-5bcf-11ea-8244-371d183d97d9.png)

**Comment by SevenSpheres** [comment]
AFAIK the OEC is no longer maintained, so this likely won't be fixed. Just use the [NASA Exoplanet Archive](https://exoplanetarchive.ipac.caltech.edu/).

**Comment by hannorein** [comment]
You could just fork it and take it over!

**Comment by SevenSpheres** [comment]
@hannorein oh wow you replied! I thought OEC was dead!

If you're still active, why are there no longer updates, and why don't you merge #1079 from 2018?

**Comment by hannorein** [comment]
This has been fixed.
