### ISSUE TITLE
Provide sources for data

### ISSUE THREAD

**Issue by SevenSpheres** [OpenExoplanetCatalogue/open_exoplanet_catalogue#1096]
If the Open Exoplanet Catalogue is still maintained (I'm not sure how to interpret @hannorein's comment in #1095), probably the most important thing that needs to be done is to provide sources for data *directly in the XML files*, not just buried in the commit history.

**Comment by hannorein** [comment]
I really like the idea to get the data source from the commit history. That was kind of the idea of the OEC in the first place. The oec_meta repository contains some of that information. I'll work on automatically importing data from other sources in the next few weeks. Hopefully this will lead to a bit more consistency in the commit history...

**Comment by SevenSpheres** [comment]
> I really like the idea to get the data source from the commit history.

Why, there is literally no way to find data sources other than looking through the commit history.
