### ISSUE TITLE
Can't find Teegarden's Star

### ISSUE THREAD

**Issue by Zireael07** [OpenExoplanetCatalogue/open_exoplanet_catalogue#1118]
It has two exoplanets, discovered in 2019... :confused:  The list has Ross 508 b, discovered literally days ago, and not this?

**Comment by hannorein** [comment]
It's here: http://www.openexoplanetcatalogue.com/planet/GJ%201061%20d/

**Comment by Zireael07** [comment]
Hm, can we have some way of recognizing alternate names for some stars then?

**Comment by hannorein** [comment]
You're welcome to add some alternative names..

**Comment by Zireael07** [comment]
Belay that, I found out how you do alternative names, but I think you are mistaken. SIMBAD doesn't list GJ 1061 as one of the alternative names for Teegarden's: https://simbad.cds.unistra.fr/simbad/sim-id?Ident=NAME+Teegarden%27s+star while listing GJ 1061 separately: https://simbad.cds.unistra.fr/simbad/sim-id?Ident=GJ1061&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

(I'd do a PR or shoot you a mail, but I want to be certain which file to edit)

**Comment by SevenSpheres** [comment]
Yes, GJ 1061 is different from Teegarden's Star. However, Teegarden's Star *is* included in the database as [GAT 1370](http://www.openexoplanetcatalogue.com/planet/GAT%201370%20b/). Probably the default name should be changed.

**Comment by hannorein** [comment]
I'm not sure it's worth changing the default name. A search will always reveal the planets. But if you think otherwise, by all means, send me a pull request (and run the cleanup script beforehand to check for consistency errors).
