### ISSUE TITLE
Cleanup MOA and OGLE names

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/open_exoplanet_catalogue#220]
Look up papers to find predominant syntax.

**Comment by ajtribick** [comment]
Main ones to fix look to be

* OGLE-05-071L --> OGLE-2005-BLG-071L
* OGLE-05-169L --> OGLE-2005-BLG-169L
* OGLE-05-390L --> OGLE-2005-BLG-390L
* OGLE-06-109L --> OGLE-2006-BLG-109L
* OGLE235-MOA53 --> ?

Problem with the last one is it is usually written with both designations (microlensing event is OGLE-2003-BLG-235/MOA 2003-BLG-53, lens system has the L appended to both), but the forward slash is impossible in the file name.

Maybe go with OGLE-2003-BLG-235L.xml, and add both names to the system tag?

**Comment by hannorein** [comment]
That sounds good.
