### ISSUE TITLE
Add remaining parameters for these new Kepler planets

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/open_exoplanet_catalogue#443]
https://www.cfa.harvard.edu/~torres/smallHZ/smallHZplanets.pdf

**Comment by hannorein** [comment]
c15bb80cc5f41cb85d07d76d2f1c700c0ee82d3b contains most of the data, but whatever is missing should be added

**Comment by ajtribick** [comment]
I'll take this one.
