### ISSUE TITLE
Add new KOIs

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/open_exoplanet_catalogue#448]
http://arxiv.org/abs/1501.01486

**Comment by Sol-d** [comment]
please assign to me.
Question: Is this the correct way: ?
KOI-206 is already in OEC; i will rename it to Kepler-433 and update it necessary
KOI-614 is not in OEC, i will add Kepler-434
KOI-680 is already in OEC; i will rename it to Kepler-435 and update it necessary

**Comment by hannorein** [comment]
Don't rename the system if it's already in the catalogue. Just add the Kepler name as an alternative identifier (the first person who discovers the planet gets to name it).
