### ISSUE TITLE
missing xml tags

### ISSUE THREAD

**Issue by Sol-d** [OpenExoplanetCatalogue/open_exoplanet_catalogue#473]
i checked the repository an found:
the list tag in planet is missing (must be at least Controversial OR Confirmed planets):
Kepler-296
Kepler-78
BD+49 828
HD 95127
HD 216536

and perhaps least important:
the description tag is missing in:
Kepler-78
BD+49 828
HD 95127
HD 216536

**Comment by hannorein** [comment]
Thanks for noticing. I'll add this check to the cleanup script and will fix those planet above.

**Comment by hannorein** [comment]
Closed in 493b35d2a28ea7300f3bf961d112cd0861280ab4

**Comment by Sol-d** [comment]
Kepler-296 has still no "Controversial" OR "Confirmed planets"

**Comment by hannorein** [comment]
Hopefully now really closed in 50f1e193ba4cb500987f2c415a8eb03dee01edfe
