### ISSUE TITLE
Add "Habitable Zone" field in options

### ISSUE THREAD

**Issue by Karlon** [OpenExoplanetCatalogue/open_exoplanet_catalogue#480]
Any planet that is calculated to be in the habitable zone, should be marked as being in the habitable zone. So when a user ticks "Habitable zone" on the options at http://www.openexoplanetcatalogue.com/systems/ - he/she can get a list of the planets that are in the habitable zone. This is efficient and will be of extremely great use to extraterrestrial researchers.

**Comment by hannorein** [comment]
@Karlon, I'm not sure if you are serious about all these issues you open. This one does not belong here, reopen it in this repository: https://github.com/OpenExoplanetCatalogue/oec_web
