### ISSUE TITLE
Update 30 Ari

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/open_exoplanet_catalogue#495]
http://www.jpl.nasa.gov/news/news.php?feature=4500

**Comment by ajtribick** [comment]
I'll take this one.

**Comment by Sol-d** [comment]
great new informations! i just observed this system some weeks ago: http://www.lx200.de/img/ep-30-ariB-20150206.jpg

**Comment by hannorein** [comment]
Wow. Nice!

**Comment by Sol-d** [comment]
this issue has the "data entry" tag, but the lastupdated is still 2009-11-27.
i thought, changes like data changes or structure changes lead to a new lastupdated date
am i wrong?

**Comment by ajtribick** [comment]
Well the lastupdated tag is associated with the *planet*, and the planet data was not updated. There is no lastupdated tag on stars or binaries.

**Comment by Sol-d** [comment]
Ok, i Understand. Thanks
