### ISSUE TITLE
K2 Planets

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/open_exoplanet_catalogue#534]
I think we don't have those ones yet:
http://arxiv.org/abs/1503.07866

**Comment by Sol-d** [comment]
Please assign to me

**Comment by Sol-d** [comment]
Only one exoplanet in the paper is named with the ending "b". All others only named by the ".0x" naming.
Question: Do we (OEC) add generally .01 as "b" and .02 as "c" and so on? - In other words: Who assigns the b,c,d names?

**Comment by hannorein** [comment]
Asking the authors...

**Comment by hannorein** [comment]
From Ben Montet:

"Presumably they'll get K2-XXb names after acceptance. I'm writing XXXXXXXXX-b in proposals for validated planets"

**Comment by hannorein** [comment]
So I'd say we go with XXXXX b for now.

**Comment by benmontet** [comment]
@Sol-d: The official "K2-NNb" numbers are assigned only after acceptance (following http://exoplanetarchive.ipac.caltech.edu/docs/K2Numbers.html). 

We use EPIC XXXXXXXXXb/XXXXXXXXX.01 interchangeably in conversation. Usually .01/.02/.03 are in the order of discovery and b/c/d are in the order of validation/confirmation. In this case everything should line up between the two, but that isn't always the case! (Kepler-32 is a good example of this). Any convention should be fine, so I'd recommend just being consistent with what you're currently doing. Except for K2-NNb, as that isn't official until NExScI says it is.

**Comment by ajtribick** [comment]
Personally I think that for the sake of future-proofing, the letter designations are not introduced until they have been definitively assigned. In the course of the Kepler cleanup I ran into a few cases where the letters had been assigned on the basis .01=b, .02=c etc. that were inconsistent with the later naming that was eventually applied (a pull request related to this issue will be sent in the near future). This then requires subsequent cleanup and also distinguishing these from the cases where there is a genuine mismatch between lettering systems (KOI-314/Kepler-138 is the first example that comes to mind), and essentially makes the catalog rather less reliable as a data source.

**Comment by hannorein** [comment]
Let's make the primary name XXXX.01 as this is what @benmontet named them in his paper. Let's also add the XXXX b name. It doesn't hurt to have an extra name and I think the risk of a different letter designation being used in the future is small. 

As a general comment: Let's try to spend less time on the naming issues and more on the actual data.

**Comment by hannorein** [comment]
Partly added in #537

**Comment by hannorein** [comment]
Closed with #538
