### ISSUE TITLE
Update τ Boo

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#554]
http://arxiv.org/abs/1504.00491

**Comment by Sol-d** [comment]
Please assign to me

**Comment by Sol-d** [comment]
sorry, i have to pass this issue to another member, because i am not enough familiar with binary systems

**Comment by ajtribick** [comment]
Ideally we should get #306 out of the way, would make adding visual binary star orbits a bit easier (typical convention for ω is reversed relative to that for RV planets).

**Comment by ajtribick** [comment]
Please assign this one to me.
