### ISSUE TITLE
Cluster planets

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#562]
I think it would be useful to indicate the exoplanets that are located in stellar clusters, e.g. via a child of the `<system>` tag. I'm thinking something along the following lines might be useful:

```xml
<system>
	<name>SAND364</name>
	<name>NGC 2682 SAND 364</name>
	<rightascension>08 49 57</rightascension>
	<declination>+11 41 33</declination>
	<distance errorminus="50" errorplus="50">750</distance>
	<cluster type="open">
		<name>M 67</name>
		<name>NGC 2682</name>
	</cluster>
	<star>
		<!-- etc. -->
	</star>
</system>
```

Thoughts?

**Comment by hannorein** [comment]
I think that's a good idea. Is there already a database out there that can find clusters for a given star?

**Comment by ajtribick** [comment]
SIMBAD seems to list clusters under the "parents" link in the hierarchy section, but as far as I am aware this is not accessible via the script submission which makes this harder to automate.
