### ISSUE TITLE
missing scientific paper

### ISSUE THREAD

**Issue by Sol-d** [OpenExoplanetCatalogue/open_exoplanet_catalogue#634]
there is no link to a scientific paper for Kepler-42 (KOI 961, KIC 8561063)

**Comment by Sol-d** [comment]
http://arxiv.org/pdf/1201.2189.pdf

**Comment by Sol-d** [comment]
please add the paper to the HTML page of Kepler-42 "Scientific references and contributors"

**Comment by hannorein** [comment]
Hm. The easiest way is to make a trivial commit on the file and add it to the commit message.

**Comment by Sol-d** [comment]
close
