### ISSUE TITLE
K2 names

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#639]
Add these names (K2-4 through K2-19) to the relevant EPIC planets
http://exoplanetarchive.ipac.caltech.edu/docs/exonews_archive.html#17July2015

**Comment by ajtribick** [comment]
Also looks like some of the parameters have been updated since the initial version of the discovery paper.

http://arxiv.org/abs/1503.07866

**Comment by Sol-d** [comment]
That is part, please assign to me
