### ISSUE TITLE
Update 2M 044144

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#680]
Including adding the Aab binary (should the ~19 Jupiter masses object Ab be represented as a planet or a star?)
http://arxiv.org/abs/1509.01658

**Comment by hannorein** [comment]
I'd say star. In general, I'd go with whatever the paper says. It might be very hard for us to always make an informed decision for every case. And having a single number as a cut-off might also be to simplistic.
