### ISSUE TITLE
Gliese 504 - older and more massive?

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#766]
Anyone able to access this paper http://cdsads.u-strasbg.fr/abs/2015ApJ...806..163F
Looks like Gliese 504 b may be a brown dwarf rather than a planet.

**Comment by hannorein** [comment]
Send me an e-mail and I'll send it to you hanno.rein@utoronto.ca

**Comment by ajtribick** [comment]
Another update http://arxiv.org/abs/1511.09183
