### ISSUE TITLE
Maximum RV time

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#780]
Ran into this while going through the old RV orbits: occasionally the orbital phase is given in terms of the epoch of maximum RV, for eccentric orbits this is not particularly straightforward to convert to either transit time or periastron time (and the error propagation can end up giving huge error bars at the end of it). Example: http://fr.arxiv.org/abs/1412.6591

Therefore I think it makes sense to add `<maximumrvtime>` to the elements, taking the same attributes as `<transittime>` and `<periastrontime>`.

**Comment by hannorein** [comment]
Hm. Interesting. And I agree, there is no easy way to covert this to a phase, especially when some other orbital parameters are not know or not well constrained. I'm happy to add `<maximumrvtime>`.
