### ISSUE TITLE
Applegate mechanism

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#810]
http://arxiv.org/abs/1512.01960

Raises questions for some systems about whether the observed timing variations are actually due to orbiting planets. Maybe some of the planets should be put on the "controversial" list?

**Comment by hannorein** [comment]
Really interesting. 

I think we should keep the planets as they are for know, but keep an eye open. As far as I interpret the results, the Applegate mechanism can produce variations comparable to the planet ones, but it's not clear if that is indeed the case.
