### ISSUE TITLE
Add HD 7449 binary star information

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#822]
http://arxiv.org/abs/1512.04540

**Comment by ajtribick** [comment]
Please assign this one to me

**Comment by ajtribick** [comment]
What should happen with HD 7449 c? From what I can see the long-period variation is now associated with the stellar companion rather than an additional planet, leaving the system with only the "b" planet. Which of "controversial" or "retracted" should be used here?

**Comment by hannorein** [comment]
I'd say controversial.

**Comment by ajtribick** [comment]
I'm considering holding off on updating the planet parameters: the values given do not make sense. From table 3 the implied radial velocity semi-amplitude for a star of 1.05 stellar masses is ~240 m/s, while the plot shown in figure 2 shows the semi-amplitude around 20-25 m/s, i.e. out by a factor of ~10.

**Comment by hannorein** [comment]
Hm. Strange. These are well known people. Maybe wait for the accepted version to appear in the journal.

**Comment by ajtribick** [comment]
Contacted and confirmed there is a mistake in the mass value. I'm going to hold off until the updated paper is ready.
