### ISSUE TITLE
K2: Five Planets Transiting a Ninth Magnitude Star

### ISSUE THREAD

**Issue by Sol-d** [OpenExoplanetCatalogue/open_exoplanet_catalogue#924]
http://arxiv.org/abs/1606.08441

**Comment by LeafyLi** [comment]
Hello, I'm a beginner, how can I help with this or any other part of the project?

**Comment by hannorein** [comment]
The task is to transfer all the data in the paper to an xml file in the right format. It helps if you have a background in astrophysics.

**Comment by ajtribick** [comment]
This one has been done, issue can be closed.
