### ISSUE TITLE
UTF-8 encoding in xml files

### ISSUE THREAD

**Issue by migueldvb** [OpenExoplanetCatalogue/open_exoplanet_catalogue#98]
I think that it would be helpful to use Unicode encoding in xml file to store characters like the greek letters in object names and other non-ascii characters in constellation names, perhaps in addition to the current version of the name fields.

**Comment by ajtribick** [comment]
The cleanup script converts the XML to UTF-8, and without an encoding declaration or UTF-16/UTF-32 byte-order mark XML defaults to UTF-8 anyway. It would be possible the encoding explicit by altering the cleanup script to output the XML declaration (and commit the relevant changes to all the system files).

**Comment by hannorein** [comment]
What's wrong with UTF-8?

**Comment by ajtribick** [comment]
Nothing wrong with it. Just pointing out that the files are already in UTF-8, so no need to make any changes for this issue. Outputting the XML declaration would be a possibility to make it more explicit that the files are UTF-8, but it's very much non-essential. I think this one can be closed.

**Comment by hannorein** [comment]
Ah. Ok. I think it's ok to leave the UTF-8 encoding implicit. Adding an identical declaration to every file seems to be an overkill.
