### ISSUE TITLE
Kepler-70 system missing from database

### ISSUE THREAD

**Issue by MEMcNeil** [OpenExoplanetCatalogue/open_exoplanet_catalogue#980]
I'm a newcomer here, so I'm not sure how to approach dealing with this kind of issue, but it appears that a half-decade-known planetary system, with two possibly three planets -- to wit, Kepler-70 (aka KOI 55, KIC 05807616, and KPD 1943+4058) -- is missing from the database, nor does a search here for "Kepler-70" turn up anything.

According to Wikipedia, along with the Extrasolar Planets Encyclopaedia, the Kepler-70 system (along with its planets 70b and 70c, at least) exists, and these two planets are "confirmed" (there may also be a 70c):

http://exoplanet.eu/catalog/kepler-70__b/
http://exoplanet.eu/catalog/kepler-70_c/

An interesting blog writeup on the system:

https://jamesrushford.wordpress.com/2013/10/22/kepler-70b-the-coolest-exoplanet/

The original Nature journal article (S. Charpinet, et al., "A compact system of small planets around a former red-giant star," Nature, 480, 496–499 (22 December 2011);  doi:10.1038/nature10631:

http://www.nature.com/nature/journal/v480/n7378/full/nature10631.html
http://www.nature.com/nature/journal/v480/n7378/fig_tab/nature10631_T1.html

Very interestingly, according to that Nature piece, the two planets 70b and c (the exposed residual rocky-metal cores of otherwise completely _evaporated_ gas-giant planets -- which even so still possess about 0.759 and 0.867 of the radius of the Earth) shine at temperatures of _9,115 K_ and _8,094 K_ respectively ("," = thousands separator) -- which is to say, far hotter than the (surface) temperature of our own Sun!

Meanwhile, their star (the exposed residual helium core of a star which had entered the red-giant phase) -- until expanding to envelop the orbits of two (or possibly three) great gas-giant planets, whose paths sweeping through what were now the outer layers of the star literally blew away its remaining hydrogen layers (only about 1% of the star is hydrogen nowadays), leaving its (still helium-fusing) core as basically all there is left of the star!

This exposed helium core of an aging star (with only about half [0.496] of the Sun's mass, and 20% [0.203] of its radius) radiates fiercely at a "surface" temperature of 27,730 K (!) -- classifying it as a "subdwarf" of spectral type "B", or a star of type "sdB."

In any event, Kepler-70 and its worlds certainly appear to me to belong in the database.

**Comment by hannorein** [comment]
The system is in the database under KOI-55. As the description points out:  This planet's existence has been challenged on the basis of the extended dataset showing amplitude variations and complex frequency structure around this period. If you think this should be changed, please submit a pull request. I'll close this for now.

**Comment by MEMcNeil** [comment]
Hm, I see what you mean. Yet, when I go to the Exoplanet app settings — and turn on the “Kepler Objects of Interest (4)” category to be displayed — as the numeral in parenthesis with that setting indicates, only FOUR objects show up, none of which is KOI-55. Where are all the rest of the KOI's — in the Exoplanet database display, that is, since they DO appear in the Open Exoplanet Catalogue here.

**Comment by hannorein** [comment]
It's the category "controversial" that you want to turn on. Go to database, then options, select the list.

**Comment by MEMcNeil** [comment]
Ah! Thanks.
